package routers

import (
	"github.com/beego/beego/v2/server/web"
	"github.com/hanc00l/nemo_go/v3/pkg/web/controllers"
)

func InitRouter() {
	web.CtrlGet("/", (*controllers.LoginController).IndexAction)
	web.CtrlPost("/", (*controllers.LoginController).LoginAction)
	web.CtrlGet("/logout", (*controllers.LoginController).LogoutAction)

	web.CtrlGet("/dashboard", (*controllers.DashboardController).IndexAction)
	web.CtrlPost("/dashboard-workspace-list", (*controllers.DashboardController).GetUserAvailableWorkspaceAction)
	web.CtrlPost("/dashboard-workspace-change", (*controllers.DashboardController).ChangeUserWorkspaceAction)
	web.CtrlPost("/dashboard-asset-count", (*controllers.DashboardController).StatisticsAssetAction)
	web.CtrlPost("/dashboard-asset-chart", (*controllers.DashboardController).AssetChartDataAction)
	web.CtrlPost("/dashboard-vul-chart", (*controllers.DashboardController).VulChartDataAction)
	web.CtrlPost("/dashboard-task-chart", (*controllers.DashboardController).TaskChartDataAction)
	web.CtrlPost("/dashboard-user-chart", (*controllers.DashboardController).UserChartDataAction)

	web.CtrlGet("/workspace-list", (*controllers.WorkspaceController).IndexAction)
	web.CtrlPost("/workspace-list", (*controllers.WorkspaceController).ListAction)
	web.CtrlPost("/workspace-get", (*controllers.WorkspaceController).GetAction)
	web.CtrlGet("/workspace-add", (*controllers.WorkspaceController).AddIndexAction)
	web.CtrlGet("/workspace-edit", (*controllers.WorkspaceController).EditIndexAction)
	web.CtrlPost("/workspace-save", (*controllers.WorkspaceController).SaveAction)
	web.CtrlPost("/workspace-delete", (*controllers.WorkspaceController).DeleteAction)

	web.CtrlGet("/user-list", (*controllers.UserController).IndexAction)
	web.CtrlPost("/user-list", (*controllers.UserController).ListAction)
	web.CtrlPost("/user-get", (*controllers.UserController).GetAction)
	web.CtrlGet("/user-add", (*controllers.UserController).AddIndexAction)
	web.CtrlPost("/user-add", (*controllers.UserController).AddSaveAction)
	web.CtrlPost("/user-update", (*controllers.UserController).UpdateAction)
	web.CtrlPost("/user-delete", (*controllers.UserController).DeleteAction)
	web.CtrlPost("/user-reset-password", (*controllers.UserController).ResetPasswordAction)
	web.CtrlPost("/user-workspace-list", (*controllers.UserController).ListUserWorkspaceAction)
	web.CtrlPost("/user-workspace-update", (*controllers.UserController).UpdateUserWorkspaceAction)

	web.CtrlGet("/org-list", (*controllers.OrganizationController).IndexAction)
	web.CtrlPost("/org-list", (*controllers.OrganizationController).ListAction)
	web.CtrlPost("/org-get", (*controllers.OrganizationController).GetAction)
	web.CtrlPost("/org-all-list", (*controllers.OrganizationController).GetAllAction)
	web.CtrlGet("/org-add", (*controllers.OrganizationController).AddIndexAction)
	web.CtrlPost("/org-add", (*controllers.OrganizationController).AddSaveAction)
	web.CtrlPost("/org-update", (*controllers.OrganizationController).UpdateAction)
	web.CtrlPost("/org-delete", (*controllers.OrganizationController).DeleteAction)

	web.CtrlGet("/profile-list", (*controllers.ProfileController).IndexAction)
	web.CtrlPost("/profile-list", (*controllers.ProfileController).ListAction)
	web.CtrlGet("/profile-edit", (*controllers.ProfileController).EditIndexAction)
	web.CtrlPost("/profile-get", (*controllers.ProfileController).GetAction)
	web.CtrlGet("/profile-add", (*controllers.ProfileController).AddIndexAction)
	web.CtrlPost("/profile-save", (*controllers.ProfileController).SaveAction)
	web.CtrlPost("/profile-delete", (*controllers.ProfileController).DeleteAction)

	web.CtrlGet("/maintask-list", (*controllers.MainTaskController).IndexAction)
	web.CtrlPost("/maintask-list", (*controllers.MainTaskController).ListAction)
	web.CtrlGet("/maintask-add", (*controllers.MainTaskController).AddIndexAction)
	web.CtrlPost("/maintask-save", (*controllers.MainTaskController).AddSaveAction)
	web.CtrlPost("/maintask-profile-list", (*controllers.MainTaskController).GetTaskProfileListAction)
	web.CtrlPost("/maintask-delete", (*controllers.MainTaskController).DeleteAction)
	web.CtrlGet("/maintask-info", (*controllers.MainTaskController).InfoIndexAction)
	web.CtrlPost("/maintask-info", (*controllers.MainTaskController).InfoAction)
	web.CtrlPost("/maintask-executor-tasks", (*controllers.MainTaskController).InfoExecutorTaskAction)
	web.CtrlPost("/maintask-executor-task-delete", (*controllers.MainTaskController).DeleteExecutorTaskAction)
	web.CtrlPost("/maintask-change-cron-status", (*controllers.MainTaskController).ChangeCronTaskStatusAction)
	web.CtrlPost("/maintask-redo", (*controllers.MainTaskController).RedoMaintaskAction)
	web.CtrlGet("/maintask-tree", (*controllers.MainTaskController).MaintaskTreeAction)
	web.CtrlPost("/maintask-tree-data", (*controllers.MainTaskController).MaintaskTreeDataAction)

	web.CtrlGet("/asset-list", (*controllers.AssetController).IndexAction)
	web.CtrlPost("/asset-list", (*controllers.AssetController).ListAction)
	web.CtrlPost("/asset-http-content", (*controllers.AssetController).AssetHttpContentAction)
	web.CtrlPost("/asset-statistic", (*controllers.AssetController).AssetStatisticsAction)
	web.CtrlPost("/asset-delete", (*controllers.AssetController).DeleteAction)
	web.CtrlPost("/asset-memo-content", (*controllers.AssetController).AssetMemoAction)
	web.CtrlPost("/asset-memo-update", (*controllers.AssetController).UpdateMemoAction)
	web.CtrlPost("/asset-export", (*controllers.AssetController).ExportAction)
	web.CtrlGet("/asset-import", (*controllers.AssetController).ImportIndexAction)
	web.CtrlPost("/asset-import", (*controllers.AssetController).ImportSaveAction)
	web.CtrlPost("/asset-block", (*controllers.AssetController).BlockAssetAction)

	web.CtrlGet("/custom-index", (*controllers.CustomController).IndexAction)
	web.CtrlPost("/custom-load", (*controllers.CustomController).LoadAction)
	web.CtrlPost("/custom-save", (*controllers.CustomController).SaveAction)

	web.CtrlGet("/vul-list", (*controllers.VulController).IndexAction)
	web.CtrlPost("/vul-list", (*controllers.VulController).ListAction)
	web.CtrlGet("/vul-info", (*controllers.VulController).InfoIndexAction)
	web.CtrlPost("/vul-info", (*controllers.VulController).InfoAction)
	web.CtrlPost("/vul-delete", (*controllers.VulController).DeleteAction)
	web.CtrlPost("/vul-load-pocfile", (*controllers.VulController).LoadPocFileAction)

	web.CtrlGet("/worker-list", (*controllers.WorkerController).IndexAction)
	web.CtrlPost("/worker-list", (*controllers.WorkerController).ListAction)
	web.CtrlPost("/worker-edit", (*controllers.WorkerController).EditWorkerAction)
	web.CtrlPost("/worker-reload", (*controllers.WorkerController).ManualReloadWorkerAction)
	web.CtrlPost("/worker-update", (*controllers.WorkerController).ManualUpdateWorkerAction)
	web.CtrlPost("/worker-init", (*controllers.WorkerController).ManualInitWorkerAction)
	web.CtrlPost("/worker-sync", (*controllers.WorkerController).ManualSyncWorkerAction)
	web.CtrlPost("/worker-stop", (*controllers.WorkerController).ManualStopWorkerAction)

	web.CtrlGet("/notify-list", (*controllers.NotifyController).IndexAction)
	web.CtrlPost("/notify-list", (*controllers.NotifyController).ListAction)
	web.CtrlPost("/notify-delete", (*controllers.NotifyController).DeleteAction)
	web.CtrlPost("/notify-get", (*controllers.NotifyController).GetAction)
	web.CtrlGet("/notify-add", (*controllers.NotifyController).AddIndexAction)
	web.CtrlPost("/notify-add", (*controllers.NotifyController).AddSaveAction)
	web.CtrlGet("/notify-update", (*controllers.NotifyController).UpdateIndexAction)
	web.CtrlPost("/notify-update", (*controllers.NotifyController).UpdateAction)
	web.CtrlPost("/notify-list-select", (*controllers.NotifyController).ListSelectNotifyAction)

	web.CtrlGet("/runtimelog-list", (*controllers.RuntimeLogController).IndexAction)
	web.CtrlPost("/runtimelog-list", (*controllers.RuntimeLogController).ListAction)
	web.CtrlPost("/runtimelog-delete", (*controllers.RuntimeLogController).DeleteAction)
	web.CtrlPost("/runtimelog-batch-delete", (*controllers.RuntimeLogController).BatchDeleteAction)
	web.CtrlGet("/accesslog-list", (*controllers.AccessLogController).IndexAction)
	web.CtrlPost("/accesslog-list", (*controllers.AccessLogController).ListAction)
	web.CtrlPost("/accesslog-file", (*controllers.AccessLogController).AccessLogFilesAction)

	web.CtrlGet("/config-server", (*controllers.ConfigController).ServerIndexAction)
	web.CtrlGet("/config-worker", (*controllers.ConfigController).WorkerIndexAction)
	web.CtrlPost("/config-worker-load-config", (*controllers.ConfigController).LoadWorkerConfigAction)
	web.CtrlPost("/config-worker-save-config", (*controllers.ConfigController).SaveWorkerConfigAction)
	web.CtrlPost("/config-server-version", (*controllers.ConfigController).LoadServerVersionAction)
	web.CtrlPost("/config-change-password", (*controllers.ConfigController).ChangePasswordAction)
	web.CtrlPost("/config-worker-test-onlineapi", (*controllers.ConfigController).TestOnlineAPIKeyAction)
	web.CtrlPost("/config-worker-test-llmapi", (*controllers.ConfigController).TestLLMAPIKeyAction)

	web.CtrlGet("/pocfile-index", (*controllers.PocFileController).IndexAction)
	web.CtrlPost("/pocfile-list", (*controllers.PocFileController).ListFilesAction)
	web.CtrlPost("/pocfile-upload", (*controllers.PocFileController).UploadFileAction)
	web.CtrlGet("/pocfile-download", (*controllers.PocFileController).DownloadFileAction)
	web.CtrlPost("/pocfile-delete", (*controllers.PocFileController).DeleteFileAction)
	web.CtrlGet("/pocfile-search", (*controllers.PocFileController).SearchFilesAction)
	web.CtrlPost("/pocfile-createFolder", (*controllers.PocFileController).CreateFolderAction)
}
